import {defineNoteConfig} from 'vuepress-theme-plume'

export const doc = defineNoteConfig({
    dir: 'doc',
    link: '/doc/',
    sidebar: [{
            items: [
                '/doc/crud-doc/',
                '/doc/crud-page/',
                '/doc/crud-search/',
                '/doc/crud-head/',
                '/doc/crud-row/',
                '/doc/crud-column/',
                '/doc/crud-dic/',
                '/doc/crud-menu/',
                '/doc/crud-fun/',
                '/doc/crud-text/',
                '/doc/crud-btn-slot/',
                '/doc/crud-form/',
                '/doc/crud-bind/',
                '/doc/crud-grid/',
                '/doc/crud-sum/',
                '/doc/crud-export/',
                '/doc/crud-tree/',
                '/doc/crud-children/',
                '/doc/crud-cell/',
                '/doc/crud-permission/',
                '/doc/crud-rc/',
                '/doc/crud-empty/',
                '/doc/crud-loading/',
                '/doc/crud-sortable/',
                '/doc/crud-default/',
                '/doc/crud-ajax/',
                '/doc/crud-bigcousin/',
            ],
        }],
})