import {defineNoteConfig} from 'vuepress-theme-plume'

export const form = defineNoteConfig({
    dir: 'form',
    link: '/form/',
    sidebar: [{
        text: 'form 文档',
        icon: 'fluent:form-multiple-48-filled',
        items: [
            '/form/form-doc/',
            '/form/form-input/',
            '/form/form-number/',
            '/form/form-select/',
            '/form/form-cascader/',
            '/form/form-checkbox/',
            '/form/form-radio/',
            '/form/form-date/',
            '/form/form-time/',
            '/form/form-switch/',
            '/form/form-upload/',
            '/form/form-title/',
            '/form/form-array/',
            '/form/form-dynamic/',
            '/form/form-input-tree/',
            '/form/form-input-icon/',
            '/form/form-input-table/',
            '/form/form-input-map/',
            '/form/form-input-color/',
            '/form/form-tag/',
            '/form/form-mention/',
            '/form/form-rate/',
            '/form/form-slider/',
            '/form/form-layout/',
            '/form/form-rules/',
            '/form/form-value/',
            '/form/form-submit/',
            '/form/form-slot/',
            '/form/form-dic/',
            '/form/form-cascader-item/',
            '/form/form-data/',
            '/form/form-event/',
            '/form/form-ajax/',
        ],
    }],
})